# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean bundleRelease")
    # sh "jarsigner -keystore #{ENV['KEYSTORE']} -storepass #{ENV['STORE_PASSWORD']} -keypass #{ENV['KEY_PASSWORD']}  ~/workspace/gitlab/android-cicd/app/build/outputs/bundle/release/*.aab #{ENV['KEY_ALIAS']}"
    sh('jarsigner -keystore "$KEYSTORE" -storepass "$STORE_PASSWORD" -keypass "$KEY_PASSWORD"  ~/workspace/gitlab/android-cicd/app/build/outputs/bundle/release/*.aab "$KEY_ALIAS"')
    upload_to_play_store(
      package_name: "com.richard.helloworld",
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
