# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean bundleRelease")
    # sh("jarsigner -keystore richard-release-key.jks -storepass whsy0805 -keypass whsy0805  ~/workspace/github/android-helloworld/app/build/outputs/bundle/release/*.aab richard-alias")
    upload_to_play_store(
      package_name: "com.richard.helloworld",
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
